"""Add endgame models

Revision ID: 2b3bd18344d8
Revises: c1bfac8dcae5
Create Date: 2026-08-20 12:27:28.929998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b3bd18344d8'
down_revision: Union[str, None] = 'c1bfac8dcae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endgame_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('PEONES', 'TORRES', 'PIEZAS_MENORES', 'DAMAS', name='lessoncategory'), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('initial_fen', sa.String(length=100), nullable=False),
    sa.Column('target_result', sa.String(length=20), nullable=False),
    sa.Column('audio_path', sa.String(length=255), nullable=True),
    sa.Column('podcast_script', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('endgame_lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_endgame_lessons_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_endgame_lessons_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_endgame_lessons_slug'), ['slug'], unique=True)

    op.create_table('endgame_timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('action_type', sa.Enum('MOVE_PIECE', 'HIGHLIGHT_SQUARE', 'DRAW_ARROW', 'PAUSE_FOR_QUIZ', name='actiontype'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['endgame_lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('endgame_timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_endgame_timeline_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_endgame_timeline_events_timestamp_seconds'), ['timestamp_seconds'], unique=False)

    op.create_table('user_endgame_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'MASTERED', name='lessonstatus'), nullable=False),
    sa.Column('last_listened_second', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['endgame_lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_endgame_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_endgame_progress_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_endgame_progress_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_endgame_progress_user_id'), ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_endgame_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_endgame_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_endgame_progress_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_user_endgame_progress_id'))

    op.drop_table('user_endgame_progress')
    with op.batch_alter_table('endgame_timeline_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_endgame_timeline_events_timestamp_seconds'))
        batch_op.drop_index(batch_op.f('ix_endgame_timeline_events_id'))

    op.drop_table('endgame_timeline_events')
    with op.batch_alter_table('endgame_lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_endgame_lessons_slug'))
        batch_op.drop_index(batch_op.f('ix_endgame_lessons_id'))
        batch_op.drop_index(batch_op.f('ix_endgame_lessons_category'))

    op.drop_table('endgame_lessons')
    # ### end Alembic commands ###
