"""initial_schema

Revision ID: fe831aa70a9f
Revises: 
Create Date: 2026-08-19 20:48:09.369272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe831aa70a9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gm_games',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gm_name', sa.String(length=100), nullable=False),
    sa.Column('white', sa.String(length=100), nullable=False),
    sa.Column('black', sa.String(length=100), nullable=False),
    sa.Column('event', sa.String(length=200), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('pgn', sa.Text(), nullable=False),
    sa.Column('theme_tags', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gm_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gm_games_gm_name'), ['gm_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_gm_games_theme_tags'), ['theme_tags'], unique=False)

    op.create_table('puzzles',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('fen', sa.String(length=200), nullable=False),
    sa.Column('moves', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('rating_deviation', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('nb_plays', sa.Integer(), nullable=True),
    sa.Column('themes', sa.String(length=500), nullable=True),
    sa.Column('game_url', sa.String(length=200), nullable=True),
    sa.Column('opening_tags', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('puzzles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_puzzles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_puzzles_opening_tags'), ['opening_tags'], unique=False)
        batch_op.create_index(batch_op.f('ix_puzzles_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_puzzles_themes'), ['themes'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('chess_online_nick', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('current_elo', sa.Integer(), nullable=False),
    sa.Column('target_elo', sa.Integer(), nullable=False),
    sa.Column('current_assigned_gm_game_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_assigned_gm_game_id'], ['gm_games.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('coach_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('estimated_level', sa.String(length=50), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('report_markdown', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coach_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coach_reports_id'), ['id'], unique=False)

    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('white_player', sa.String(length=100), nullable=False),
    sa.Column('black_player', sa.String(length=100), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('player_color', sa.String(length=5), nullable=False),
    sa.Column('pgn_content', sa.Text(), nullable=False),
    sa.Column('total_moves', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_id'), ['id'], unique=False)

    op.create_table('gm_consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gm_consultations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gm_consultations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gm_consultations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_gm_consultations_user_id'), ['user_id'], unique=False)

    op.create_table('processing_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('skipped_duplicate', sa.Integer(), nullable=False),
    sa.Column('skipped_not_user', sa.Integer(), nullable=False),
    sa.Column('errors_found', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_tasks_id'), ['id'], unique=False)

    op.create_table('user_analyzed_gm_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gm_game_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gm_game_id'], ['gm_games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_analyzed_gm_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_analyzed_gm_games_id'), ['id'], unique=False)

    op.create_table('user_game_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=36), nullable=True),
    sa.Column('game_type', sa.String(length=10), nullable=False),
    sa.Column('white_player', sa.String(length=150), nullable=True),
    sa.Column('black_player', sa.String(length=150), nullable=True),
    sa.Column('pgn', sa.Text(), nullable=True),
    sa.Column('fases_analisis', sa.Text(), nullable=True),
    sa.Column('momentos_criticos', sa.Text(), nullable=True),
    sa.Column('factores_posicionales', sa.Text(), nullable=True),
    sa.Column('conclusiones_plan', sa.Text(), nullable=True),
    sa.Column('gemini_feedback', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['gm_games.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_game_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_game_analyses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_game_analyses_status'), ['status'], unique=False)

    op.create_table('weekly_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_plans_id'), ['id'], unique=False)

    op.create_table('move_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('algebraic_move', sa.String(length=10), nullable=False),
    sa.Column('error_type', sa.String(length=50), nullable=False),
    sa.Column('eval_difference', sa.Integer(), nullable=False),
    sa.Column('tactical_theme', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('move_errors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_move_errors_id'), ['id'], unique=False)

    op.create_table('training_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('STRATEGY', 'TACTICS', 'ENDGAME', 'GM_GAME_ANALYSIS', name='exercisecategory'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.Column('current_count', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('weekly_plan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weekly_plan_id'], ['weekly_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_tasks_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_tasks_id'))

    op.drop_table('training_tasks')
    with op.batch_alter_table('move_errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_move_errors_id'))

    op.drop_table('move_errors')
    with op.batch_alter_table('weekly_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_plans_id'))

    op.drop_table('weekly_plans')
    with op.batch_alter_table('user_game_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_game_analyses_status'))
        batch_op.drop_index(batch_op.f('ix_user_game_analyses_id'))

    op.drop_table('user_game_analyses')
    with op.batch_alter_table('user_analyzed_gm_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_analyzed_gm_games_id'))

    op.drop_table('user_analyzed_gm_games')
    with op.batch_alter_table('processing_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_tasks_id'))

    op.drop_table('processing_tasks')
    with op.batch_alter_table('gm_consultations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gm_consultations_user_id'))
        batch_op.drop_index(batch_op.f('ix_gm_consultations_status'))
        batch_op.drop_index(batch_op.f('ix_gm_consultations_id'))

    op.drop_table('gm_consultations')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_id'))

    op.drop_table('games')
    with op.batch_alter_table('coach_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coach_reports_id'))

    op.drop_table('coach_reports')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('puzzles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_puzzles_themes'))
        batch_op.drop_index(batch_op.f('ix_puzzles_rating'))
        batch_op.drop_index(batch_op.f('ix_puzzles_opening_tags'))
        batch_op.drop_index(batch_op.f('ix_puzzles_id'))

    op.drop_table('puzzles')
    with op.batch_alter_table('gm_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gm_games_theme_tags'))
        batch_op.drop_index(batch_op.f('ix_gm_games_gm_name'))

    op.drop_table('gm_games')
    # ### end Alembic commands ###
